### ISSUE TITLE
自签证书在哪找？

### ISSUE THREAD

**Issue by a308667911** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#27]
我看到生成的配置写的是  sin www.bing.com

客户端 证书 那里 把 不检查 勾上 才通，所以 客户端 那里的证书 怎么填？

**Comment by yonggekkk** [comment]
生成二维码与分享连接直接用就是！
相关视频教程：
https://youtu.be/QwTapeVPeB0
https://youtu.be/kmTgj1DundU

**Comment by a308667911** [comment]
好吧，我用了分享链接 你那里也是 打勾的 不检查服务器证书 ，我只是想 知道 用了其他 sni 怎么使用 自签证书

**Comment by yonggekkk** [comment]
> 好吧，我用了分享链接 你那里也是 打勾的 不检查服务器证书 ，我只是想 知道 用了其他 sni 怎么使用 自签证书

更新你的客户端

**Comment by a308667911** [comment]
> > 好吧，我用了分享链接 你那里也是 打勾的 不检查服务器证书 ，我只是想 知道 用了其他 sni 怎么使用 自签证书
> 
> 更新你的客户端，，自签证书不用设置，不知道你用什么客户端？

可能你误会我的意思了，现在脚本的配置能正常使用 ....  只是 sni 域名 默认是雅虎的 ，我想知道 不验证 证书那里 为什么 要 打勾 才能正常使用 ？ 用自己的域名申请 就不用打勾 ，

**Comment by yonggekkk** [comment]
> > > 好吧，我用了分享链接 你那里也是 打勾的 不检查服务器证书 ，我只是想 知道 用了其他 sni 怎么使用 自签证书
> > 
> > 
> > 更新你的客户端，，自签证书不用设置，不知道你用什么客户端？
> 
> 可能你误会我的意思了，现在脚本的配置能正常使用 .... 只是 sni 域名 默认是雅虎的 ，我想知道 不验证 证书那里 为什么 要 打勾 才能正常使用 ？ 用自己的域名申请 就不用打勾 ，

有四个协议！各不相关！雅虎是reality协议偷证书！看上面给你的教程吧
