### ISSUE TITLE
CPU架构判断问题

### ISSUE THREAD

**Issue by dakkidaze** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#28]
Sing-box有amd64和amd64v3两个版本的可执行文件，amd64v3会使用一些新指令集，在较老的CPU上无法很好地执行（比如E5v4），此时使用v3的可执行文件会报错“This program can only be run on AMD64 processors with v3 microarchitecture support.”
解决方案也很简单，下载amd64的可执行文件即可，脚本里好像是默认下载v3的
![图片](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/13714426/d660ad4d-7d39-463c-9eb3-68a1fb7bbca3)
![图片](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/13714426/e4d3c83f-7f34-4d6b-bcda-758ebdd8ddba)

**Comment by dakkidaze** [comment]
自己反混淆看了一下，不能只以avx2作为版本判断标准，按Golang的规定要支持下图2所有指令集，我这台机器就只有avx2但是没有f16c，这个地方还需要进一步优化
![图片](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/13714426/f0ffc27e-33ae-4c6e-8bc2-46dbe29be3e6)
![图片](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/13714426/c5e62527-8826-4c0f-bf02-f2f75fd44d9d)

**Comment by yonggekkk** [comment]
> 自己反混淆看了一下，不能只以avx2作为版本判断标准，按Golang的规定要支持下图2所有指令集，我这台机器就只有avx2但是没有f16c，这个地方还需要进一步优化 ![图片](https://private-user-images.githubusercontent.com/13714426/292686459-f0ffc27e-33ae-4c6e-8bc2-46dbe29be3e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NjI0ODAsIm5iZiI6MTcwMzQ2MjE4MCwicGF0aCI6Ii8xMzcxNDQyNi8yOTI2ODY0NTktZjBmZmMyN2UtMzNhZS00YzZlLThiYzItNDZkYmUyOWJlM2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDIzNTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYmY1OGMxNjQ3MzFkMzFhZmRmZmQ4YzhiYjc3Nzg0NzQ5NzE0ZGIwNDM0YTBhNzMyMmIwYTE2YWE0Njk4MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQNvI5ZkKbGMI0UFq_j3_iPacNlLA72hv8npOqIXU2I) ![图片](https://private-user-images.githubusercontent.com/13714426/292686489-c5e62527-8826-4c0f-bf02-f2f75fd44d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NjI0ODAsIm5iZiI6MTcwMzQ2MjE4MCwicGF0aCI6Ii8xMzcxNDQyNi8yOTI2ODY0ODktYzVlNjI1MjctODgyNi00YzBmLWJmMDItZjJmNzVmZDQ0ZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDIzNTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYzBkZGEyNTM0ZDNjNjk4ZTNiOWRmMzE5MTg0MGVlNWRhNzVlMGQwMmZmNjgxYTQ1ZjUxZWE2MDJlYjVkZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8cccB_MKa3hmf2PEiWiYblFIf_-JAYNEsdWZoLaVb6Q)

感谢提醒。。。
