### ISSUE TITLE
部分vps安装后无法使用

### ISSUE THREAD

**Issue by Venompool888** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#33]
无脑安装以后4台vps有2台不能用，而且这两个vps都没有ipv6，不知道有没有关联，日志如下
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/94547252/8e3ff013-d9f3-4e0d-bf8c-0876a0531df6)
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/94547252/73721fe5-373d-4870-b2c7-0c01f3b51ee8)

vmess报错较多但是实际上hy2也不能用，别的还没测试

**Comment by yonggekkk** [comment]
> 无脑安装以后4台vps有2台不能用，而且这两个vps都没有ipv6，不知道有没有关联，日志如下 ![image](https://private-user-images.githubusercontent.com/94547252/294214251-8e3ff013-d9f3-4e0d-bf8c-0876a0531df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjIzNzAsIm5iZiI6MTcwNDQyMjA3MCwicGF0aCI6Ii85NDU0NzI1Mi8yOTQyMTQyNTEtOGUzZmYwMTMtZDlmMy00ZTBkLWJmOGMtMDg3NmEwNTMxZGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAyMzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGY0YTdhZGRlNzE0MmRhZGY4MWQwOTQ3YzUwNDEzNjk3YmQ5MzJkNTE5MWI3ZDQ0NjJiYmE5NmFlNDc3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4wYZoDj84O2cIK36OYMKUk75T6ux_6Asbx-J4l-c26Q) ![image](https://private-user-images.githubusercontent.com/94547252/294214313-73721fe5-373d-4870-b2c7-0c01f3b51ee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjIzNzAsIm5iZiI6MTcwNDQyMjA3MCwicGF0aCI6Ii85NDU0NzI1Mi8yOTQyMTQzMTMtNzM3MjFmZTUtMzczZC00ODcwLWIyYzctMGMwMWYzYjUxZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAyMzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZjE4Mzg4NzhhOWIyOTQ4NjAxOGI0YTJkZjQyODJkZGYwY2VhZDhlYzExOGRjN2I0ZmE1OWJiMTQxYjY2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N5GGHrRBRUe5UwF4bobf1xT_PzzfN4lIZxVHNTxvJjo)
> 
> vmess报错较多但是实际上hy2也不能用，别的还没测试

在群里吗？@我，VPS发我下

**Comment by bigm0re** [comment]
我是相同的情况，两台vps也是没有ipv6，是pacificrack和hostdare的

**Comment by yonggekkk** [comment]
> 我是相同的情况，两台vps也是没有ipv6，是pacificrack和hostdare的

在群里吗？发vps我试试
