### ISSUE TITLE
大佬，Hysteria-2、Tuic-v5在小火箭shadowrocket无法使用

### ISSUE THREAD

**Issue by itlzm** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#35]
![screenshot-20240108-175731](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/19933569/72d93fb6-f95f-4339-9eee-e2be149f967f)
大佬，昨天在VPS上安装成功， Vmess-ws、Vless-reality 在小火箭shadowrocket（版本2.2.43）上可以使用，
Hysteria-2、Tuic-v5在小火箭shadowrocket无法使用，
在手机上安装sing-box后导入SFA/SFI/SFW统一配置文件（/etc/s-box/sing_box_client.json），结果和shadowrocket是一样的，
请问下是什么原因？

**Comment by itlzm** [comment]
> 什么vps？换个系统试试

Oracle cloud白嫖的，换系统要重新创建实例，前面已经反复创建终止了很多实例，用了你的脚本才成功，不想再折腾了，现在argo的链接还能用，等后面不行了再说吧，感谢

**Comment by wfygefjgd** [comment]
手动输入可以的，如果是直接分享到小火箭使用不了

**Comment by lihaokey** [comment]
> 手动输入可以的，如果是直接分享到小火箭使用不了

是我自己傻了，以为不能用，其实可以用。当时测试没有速度以为不行，实际可以的。因为测试是TCP，所以Hysteria-2、Tuic-v5没有速度。
