### ISSUE TITLE
执行13-管理WARP脚本时无法获得IPV4和V6地址

### ISSUE THREAD

**Issue by donkeykangwang10** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#36]
四个协议都能正常工作，也能获得VPS的IPV4地址，但是想进一步部署Warp时，显示无法获得IPV4,V6地址。脚本命令行也有一些错误提示如下：

请稍等5秒，检测 Netflix 与 ChatGPT 解锁情况
environment: line 115: curl: command not found
environment: line 116: curl: command not found
-----------------------------------------------------------------------
 IPV4地址：不存在IPV4地址
-----------------------------------------------------------------------
 IPV6地址：不存在IPV6地址

**Comment by yonggekkk** [comment]
什么VPS。安装curl失败？
ubuntu或者debian运行下apt update -y && apt install curl -y

**Comment by donkeykangwang10** [comment]
> 什么VPS。安装curl失败？ ubuntu或者debian运行下apt update -y && apt install curl -y

甲骨文的VPS，curl已经安装了最新版本。

**Comment by yonggekkk** [comment]
> > 什么VPS。安装curl失败？ ubuntu或者debian运行下apt update -y && apt install curl -y
> 
> 甲骨文的VPS，curl已经安装了最新版本。

输入curl ip.sb有没有反应，如果没有，重装系统

**Comment by yonggekkk** [comment]
> > > 什么VPS。安装curl失败？ ubuntu或者debian运行下apt update -y && apt install curl -y
> > 
> > 
> > 甲骨文的VPS，curl已经安装了最新版本。
> 
> 输入curl ip.sb有没有反应，如果没有，卸载warp

**Comment by donkeykangwang10** [comment]
> > > 什么VPS。安装curl失败？ ubuntu或者debian运行下apt update -y && apt install curl -y
> > 
> > 
> > 甲骨文的VPS，curl已经安装了最新版本。
> 
> 输入curl ip.sb有没有反应，如果没有，卸载WARP

Curl ip.sb有反应，输出的是VPS的IP V4地址

**Comment by donkeykangwang10** [comment]
选择安装socks5-WARP, 出现以下信息，有好几处都出现执行的错误。

 任意选择适合自己的warp现实方案（选项1、2、3，可单选，可多选共存）
 进入脚本快捷方式：cf
 =================================================================
  1. 方案一：安装/切换WARP-GO
  2. 方案二：安装Socks5-WARP
  3. 方案三：生成WARP-Wireguard配置文件、二维码
  4. 卸载WARP
 -----------------------------------------------------------------
  5. 关闭、开启/重启WARP
  6. WARP其他选项
  7. WARP三类账户升级/切换
  8. 更新CFwarp安装脚本
  9. 更新WARP-GO内核
 10. 将当前WARP-GO内核替换为WGCF-WARP内核
  0. 退出脚本 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
environment: line 56: curl: command not found
 当前 CFwarp-yg 脚本版本号：
 请先选择方案（1、2、3） ，安装想要的warp模式
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 VPS系统信息如下：
 操作系统: Ubuntu 20.04.6 LTS  内核版本: 5.15.0  CPU架构 : amd64v3  虚拟化类型: kvm
------------------------------------------------------------------------------------
 方案一：当前 IPV4 接管VPS出站情况如下（WARP监测已开启）
 IPV4状态：不存在IPV4地址 
------------------------------------------------------------------------------------
 方案一：当前 IPV6 接管VPS出站情况如下（WARP监测已开启）
 IPV6状态：不存在IPV6地址 
------------------------------------------------------------------------------------
IPV4与IPV6都为不存在，建议如下：
1、原来安装wgcf的，选择9切换到warp-go重装warp
2、原来安装warp-go的，选择10切换到wgcf重装warp
切记：如依旧如此，建议卸载并重启VPS，再重装方案一
------------------------------------------------------------------------------------------------
 方案二：当前 Socks5-WARP 官方客户端本地代理情况如下
 Socks5 WARP状态：未安装Socks5-WARP客户端
------------------------------------------------------------------------------------------------

 请输入数字:2
检测Socks5-WARP安装环境中……
environment: line 115: curl: command not found
environment: line 116: curl: command not found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
net-tools is already the newest version (1.60+git20180626.aebd88e-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
environment: line 631: curl: command not found
gpg: no valid OpenPGP data found.
deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] http://pkg.cloudflareclient.com/ focal main
Hit:2 http://ap-chuncheon-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal InRelease                                                     
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                      
Get:4 http://ap-chuncheon-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                    
Get:1 https://pkg.cloudflareclient.com focal InRelease [1,850 B]
Err:1 https://pkg.cloudflareclient.com focal InRelease   
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6E2DD2174FA1C3BA
Hit:5 http://ap-chuncheon-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease
Get:6 http://ap-chuncheon-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3,030 kB]
Get:7 http://ap-chuncheon-1-ad-1.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,144 kB]
Reading package lists... Done                                                                                                                                           
W: GPG error: https://pkg.cloudflareclient.com focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6E2DD2174FA1C3BA
E: The repository 'http://pkg.cloudflareclient.com focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package cloudflare-warp
environment: line 115: curl: command not found
environment: line 116: curl: command not found
environment: line 128: wget: command not found
environment: line 132: wget: command not found
cat: /root/warpip/result.csv: No such file or directory
cat: /root/warpip/result.csv: No such file or directory
安装结束，回到菜单
environment: line 442: curl: command not found
chmod: cannot access '/usr/bin/cf': No such file or directory

**Comment by yonggekkk** [comment]
你这系统有问题，是不是DD过的?重装下

**Comment by yonggekkk** [comment]
还有。。要用ubuntu22.04系统
