### ISSUE TITLE
Argo Blocked

### ISSUE THREAD

**Issue by SalarAbapour** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#37]
Hello. Argo tunnel is filtered in Iran. Can I please add another method?

**Comment by yonggekkk** [comment]
> Hello. Argo tunnel is filtered in Iran. Can I please add another method?

What methods or protocols can be run in your place?

**Comment by SalarAbapour** [comment]
If server IP is clean, tuic5, hysteria2 and vmess. But the IP of all servers are filtered immediately.

**Comment by yonggekkk** [comment]
> If server IP is clean, tuic5, hysteria2 and vmess. But the IP of all servers are filtered immediately.

How about reality or cdn？

**Comment by SalarAbapour** [comment]
Reality will filter the server IP immediately.

**Comment by yonggekkk** [comment]
> Reality will filter the server IP immediately.

only CF cdn ?

**Comment by SalarAbapour** [comment]
Some use arguments, but Singbox app does not support arguments

**Comment by SalarAbapour** [comment]
CF cdn often filter our domins

**Comment by yonggekkk** [comment]
What method are you using now?

**Comment by SalarAbapour** [comment]
Tuic5, Vmess, Hysteria2

**Comment by SalarAbapour** [comment]
But only id the vps IP is clean

**Comment by SalarAbapour** [comment]
> Some use fragment, but Singbox app does not support fragment

Fragment
