### ISSUE TITLE
argo隧道不能固定

### ISSUE THREAD

**Issue by lyp88997** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#38]
非常支持勇哥的脚本，希望勇哥能更新添加自定义argo隧道域名固定配置选项就更完美了

**Comment by yonggekkk** [comment]
> 非常支持勇哥的脚本，希望勇哥能更新添加自定义argo隧道域名固定配置选项就更完美了

2月份！下版会支持固定隧道！
