### ISSUE TITLE
443 error: unexpected status: 429 Too Many Requests（argo节点）

### ISSUE THREAD

**Issue by qfomg** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#43]
勇哥好，谢谢你的脚本，非常好用，傻瓜式。

想反馈一个问题，用的argo节点，当连接数增多后，会有“443 error: unexpected status: 429 Too Many Requests" 这个错误提示，请问有解决方法吗？谢谢你。

**Comment by yonggekkk** [comment]
> 勇哥好，谢谢你的脚本，非常好用，傻瓜式。
> 
> 想反馈一个问题，用的argo节点，当连接数增多后，会有“443 error: unexpected status: 429 Too Many Requests" 这个错误提示，请问有解决方法吗？谢谢你。

都用443？换几个端口同时用试试

**Comment by qfomg** [comment]
好的
