### ISSUE TITLE
vps 重启后 sing-box不能正常运行

### ISSUE THREAD

**Issue by xuyan74** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#45]
重启vps后 sing-box出错。vps是甲骨文 centos8。 日志如下
+0000 2024-02-27 05:55:17 INFO router: updated default interface ens3, index 2
FATAL[0000] start service: open geosite database: open geosite.db: permission denied
sing-box.service: Main process exited, code=exited, status=1/FAILURE
sing-box.service: Failed with result 'exit-code'.
sing-box.service: Service RestartSec=10s expired, scheduling restart.
sing-box.service: Scheduled restart job, restart counter is at 4.
Stopped sing-box.service.
Started sing-box.service.
+0000 2024-02-27 05:55:27 INFO router: updated default interface ens3, index 2
+0000 2024-02-27 05:55:32 WARN close outbound/wireguard[8] take too much time to finish!

**Comment by yonggekkk** [comment]
这是没装成功吗？卸载重装下，再试试重启

**Comment by xuyan74** [comment]
安装是成功的，就是vps重启后会出错，需要重新安装
