### ISSUE TITLE
甬哥，脚本有问题，出了一堆字符

### ISSUE THREAD

**Issue by vvstar1982** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#46]
截取一部分，下面还有很多。系统:Debian GNU/Linux 12 (bookworm)  内核:6.1.0  处理器:amd64v3
版本24.2.27 v2.0和上一个版本均出现此情况
另一台vps，系统:Ubuntu 22.04.3 LTS  内核:5.15.0  处理器:amd64v3  虚拟化:kvm，没问题

12. 管理 Acme 申请域名证书
13. 管理 Warp 查看Netflix/ChatGPT解锁情况
 0. 退出脚本
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
当前 Sing-box-yg 脚本版本号：24.2.27 v2.0
检测到最新 Sing-box-yg 脚本版本号：<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;c。。。。。。

**Comment by vvstar1982** [comment]
2个vps均使用了warp脚本

#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/rwkgyg\/sing-box-yg\/-\/raw\/main\/version\/version?__cf_chl_rt_tk=5okAjB1goTqE_PWbZ2Nw.RvpxtAq8ZzEbMML0FvivZI-1709105324-0.0-3517" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>

当前 Sing-box 最新正式版内核：1.8.7 (已安装)

当前 Sing-box 最新测试版内核：1.9.0-alpha.15 (可切换)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VPS状态如下：
系统:Debian GNU/Linux 12 (bookworm)  内核:6.1.0  处理器:amd64v3  虚拟化:microsoft  BBR算法:bbr

**Comment by yonggekkk** [comment]
gitlab对WARP ip的冲突。。。到时我更新下。。
