### ISSUE TITLE
无法替换为WARP Teams

### ISSUE THREAD

**Issue by a641764137** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#47]
如题，输完token后会弹出Failed to register warp: invalid character '<' looking for beginning of value提示
系统:Ubuntu 22.04.4 LTS  内核:5.15.0  处理器:amd64  虚拟化:kvm  BBR算法:bbr

**Comment by yonggekkk** [comment]
先卸载重装下

**Comment by a641764137** [comment]
> 先卸载重装下

重装过了，问题依旧，故障如下：
 请输入数字:7
1. WARP普通账户（无限流量）
2. WARP+账户（有限流量）
3. WARP Teams (Zero Trust)团队账户（无限流量）
4. Socks5+WARP+账户（有限流量）
请选择想要切换的账户类型：3
Zero Trust团队Token获取地址：https://web--public--warp-team-api--coia-mfs4.code.run/
请输入团队账户Token: 一大串token
ERROR: (WARP-Go)2024/02/28 09:35:00 Failed to register warp: invalid character '<' looking for beginning of value
共执行10次，第1次获取warp的IP中……

**Comment by yonggekkk** [comment]
有没有少复制了？上游可能出问题了！等等吧

**Comment by yonggekkk** [comment]
测试了下，正常
