### ISSUE TITLE
新脚本问题蛮多的，Hysteria-2

### ISSUE THREAD

**Issue by vvstar1982** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#48]
用链接导入的Hysteria-2信息是可以用的，但是相同服务器，对比tuic慢了很多，200ms和800ms
ios系统的sing-box，在Hysteria-2配置文件中修改了uuid和端口号，无法连接

**Comment by yonggekkk** [comment]
hy2混淆有没有影响，再看看吧。。

**Comment by vvstar1982** [comment]
vultr，centos的vps上装了最新脚本
在ios系统，sing-box1.8.7里面使用了订阅链接。没有问题。
openwrt软路由里面，设置了tuic和hy2，vultr同一台vps的，passwall测速hy2确实是800ms，tuic5还是200ms

**Comment by longyan2009** [comment]
hy2 tuic5 无法切换域名证书 warp 分流出现错误

**Comment by yonggekkk** [comment]
已更新。卸载 重装下
