### ISSUE TITLE
固定Argo Tunnel使用一天之后就断开

### ISSUE THREAD

**Issue by xiaosahuogui** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#50]
甬哥你好，我用的Euserv的纯IPV6小鸡，套了双栈Warp, 固定隧道搭建好之后节点一切正常，使用一天之后节点就不通了，登录CF发现隧道的状态变成Down, 已经连续出现两次了，好像是每隔24小时就会自动断开。

**Comment by 14790897** [comment]
怎么回事
