### ISSUE TITLE
升级脚本版本后报错

### ISSUE THREAD

**Issue by JupiterFeng** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#54]
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/134389159/c8c18df4-41a1-40f8-97de-cef0dd7bf426)
不知道该怎么办才能包留原来的配置重新安装插件

**Comment by yonggekkk** [comment]
你安装了WARP脚本吧？

**Comment by JupiterFeng** [comment]
> 你安装了WARP脚本吧？

是的,脚本内安装的

**Comment by yonggekkk** [comment]
先卸载吧，个别VPS生成的WARP IP与Gitlab有冲突。。

**Comment by JupiterFeng** [comment]
> 先卸载吧，个别VPS生成的WARP IP与Gitlab有冲突。。

我没找到卸载的命令

**Comment by yonggekkk** [comment]
1、终止warp-go： kill -15 $(pgrep warp-go)

2、终止wgcf： systemctl stop wg-quick@wgcf

输入后，进脚本卸载

**Comment by JupiterFeng** [comment]
> 先卸载吧，个别VPS生成的WARP IP与Gitlab有冲突。。
我的vps 是oracle arm 服务器

**Comment by JupiterFeng** [comment]
> 1、终止warp-go： kill -15 $(pgrep warp-go)
> 
> 2、终止wgcf： systemctl stop wg-quick@wgcf
> 
> 输入后，进脚本卸载
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/134389159/7ea26645-d726-4a19-8740-fadb118aa10d)

**Comment by yonggekkk** [comment]
不是root目录？

**Comment by JupiterFeng** [comment]
> 不是root目录？

不太清楚了,我看确实是安装在root下

![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/134389159/a0586656-1d63-4356-85f0-90b4bb01e4a6)

**Comment by yonggekkk** [comment]
命令都运行下就行了

**Comment by JupiterFeng** [comment]
> 命令都运行下就行了

执行了,但还是不行 进不到sb里面

**Comment by JupiterFeng** [comment]
我先把实例删了重新搞吧
