### ISSUE TITLE
gitlab自动更新脚本 clash-meta客户端无法使用 proxy 0 invalid reality short id

### ISSUE THREAD

**Issue by JupiterFeng** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#55]
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/134389159/032e70c0-41cf-4416-aab8-68b7a93a8cf2)
proxy 0 invalid reality short id

**Comment by yonggekkk** [comment]
realiyt的short id没生成参数吗？查看下

**Comment by JupiterFeng** [comment]
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/134389159/fc74384e-ec3a-4be0-af62-a480b5af1057)
我看是有的
