### ISSUE TITLE
一键生成的tuic-v5协议无法使用

### ISSUE THREAD

**Issue by dbguo** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#58]
在几台VPS上试过了，其它三个协议可以用，tuic-v5都不通~。虽然用不上tuic-v5，因为都用hy2代替了。但希望还是能修复一下或者干脆取消这个协议的搭建。

**Comment by yonggekkk** [comment]
应该不存在这问题，换个客户端测试

**Comment by dbguo** [comment]
> 应该不存在这个问题，换个客户端测试

对，确实是我的问题，原来最新版的v2rayN也无法支持tuic-v5，是我想当然了。手机上用Nekobox可以

**Comment by yonggekkk** [comment]
v2rayN最新版可以用呀。自签字证时，证书验证选择true

**Comment by yonggekkk** [comment]
> v2rayN最新版可以用呀。自签字证时，跳过证书验证选择true

**Comment by dbguo** [comment]
> v2rayN最新版可以用呀。自签证时，跳过证书验证选择true

谢谢，完美解决。

**Comment by huang5307** [comment]
> v2rayN最新版可以用呀。自签字证时，跳过证书验证选择true

用自己域名证书可以，用Bing证书不行。
