### ISSUE TITLE
vultr的debian系统更新后有bug

### ISSUE THREAD

**Issue by vvstar1982** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#61]
vultr的debian系统更新后有bug，另一台oracle上的ubuntu系统没什么问题。都是直接更新。

**Comment by vvstar1982** [comment]
![20240325095726](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/39043483/4fc2f44d-283d-4269-950b-fdbd4f86b92d)

**Comment by yonggekkk** [comment]
是否装了warp脚本?

**Comment by vvstar1982** [comment]
安装了，vultr和oracle的都安装了

**Comment by yonggekkk** [comment]
只能说某些VPS的IP获取与WARP IP与gitlab冲突了。你先关闭WARP
