### ISSUE TITLE
脚本卡死

### ISSUE THREAD

**Issue by lyj0309** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#62]
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/50474995/3ee5ec96-f179-4e45-9d25-35b7a428a4b7)
输入sb后一直卡着，也输入不了命令

**Comment by yonggekkk** [comment]
CTRL+C退出重新来

**Comment by lyj0309** [comment]
> CTRL+C退出重新来

还是卡，等了5分钟才出现界面，不知道卡哪里了

**Comment by yonggekkk** [comment]
重启下VPS
