### ISSUE TITLE
tg推送不全

### ISSUE THREAD

**Issue by gaodeng520** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#63]
推送sb配置显示4段
却只推送了3段，而且不完整

**Comment by yonggekkk** [comment]
应该不会～…查看下是不是没复制全？

**Comment by gaodeng520** [comment]
真的没推全，只有三段，之前两段没有问题

**Comment by yonggekkk** [comment]
发图看看

**Comment by gaodeng520** [comment]
https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/102899873/fe676610-2560-4952-a95e-bdf58b983e2b

看看

**Comment by gaodeng520** [comment]
https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/102899873/9ea708be-0c4d-4410-918b-847ce3e37fae
视频链接

**Comment by yonggekkk** [comment]
> https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/102899873/9ea708be-0c4d-4410-918b-847ce3e37fae 视频链接

方便的话先重置下TG配置信息，或者重装下脚本。我测试了没问题。
