### ISSUE TITLE
SFW面板端口问题

### ISSUE THREAD

**Issue by jpcchu** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#64]
SFW电脑客户端网页版的面板能不能自定义端口？默认是9090，希望可以更改！

**Comment by yonggekkk** [comment]
你要自定义？你可以改配置文件中的9090，然后网页自己改下就行了

**Comment by jpcchu** [comment]
配置文件是指SFW.exe？这个文件似乎已被加密!我无法编辑.

**Comment by yonggekkk** [comment]
> 配置文件是指SFW.exe？这个文件似乎已被加密!我无法编辑.

config.json
