### ISSUE TITLE
TUN模式不定时断流

### ISSUE THREAD

**Issue by lyo710** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#68]
官版immortalwrt 23.05.2，sing-box 1.8.10-1,
TUN模式开透明代理，24小时内随机性断流，症状是国内网无法访问。

DEBUG 日志
Tue Apr  9 06:56:54 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:54 [36mINFO[0m dns: exchanged aefd.nelreports.net CNAME aefd.nelreports.net.akamaized.net. 20 IN CNAME a1851.dscg2.akamai.net.
Tue Apr  9 06:56:54 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:54 [36mINFO[0m dns: exchanged aefd.nelreports.net A a1851.dscg2.akamai.net. 20 IN A 96.7.128.71
Tue Apr  9 06:56:54 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:54 [36mINFO[0m dns: exchanged aefd.nelreports.net A a1851.dscg2.akamai.net. 20 IN A 96.7.128.44
Tue Apr  9 06:56:54 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:54 [37mDEBUG[0m [[38;5;223m147767503[0m 10.15s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled
Tue Apr  9 06:56:55 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:55 [37mDEBUG[0m [[38;5;77m1193653309[0m 10.15s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled
Tue Apr  9 06:56:55 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:55 [37mDEBUG[0m [[38;5;43m1976878066[0m 10.15s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled
Tue Apr  9 06:56:55 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:55 [37mDEBUG[0m [[38;5;191m3365234175[0m 10.15s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled
Tue Apr  9 06:56:56 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:56 [37mDEBUG[0m [[38;5;218m4133292746[0m 10.15s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled
Tue Apr  9 06:56:57 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:57 [37mDEBUG[0m [[38;5;76m2945375036[0m 10.0s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled
Tue Apr  9 06:56:57 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:57 [37mDEBUG[0m [[38;5;227m3562874628[0m 10.0s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled
Tue Apr  9 06:56:57 2024 daemon.err sing-box[23783]: +0000 2024-04-08 22:56:57 [37mDEBUG[0m [[38;5;195m27936507[0m 10.0s] inbound/tun[0]: connection closed: io: read/write on closed pipe | upstream: context canceled

客户端config.json
[config.json](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/files/14912567/config.json)

**Comment by yonggekkk** [comment]
这个不清楚了，也没测试过这种模式。。

**Comment by lyo710** [comment]
用原版openwrt 23.05.3替换immortalwrt 23.05.2，貌似没有断流问题了。
