### ISSUE TITLE
勇哥你好，脚本中生成的节点名字排序优化

### ISSUE THREAD

**Issue by vbskycn** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#70]
勇哥你好，脚本中生成的  节点名字，vps的名字根在节点名的后面

可以调到节点的前面去吗，在有多个vps节点的时候看得眼睛太乱了😄

如果vps名在节点名前面那排序会好有规律。

![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/34542650/4b97d5f5-21f1-45a1-b535-e580d9a024f3)

真是烦死强迫症

![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/34542650/14fe1a4f-a764-4a02-b690-d687d160a632)

**Comment by yonggekkk** [comment]
了解。。下回更新下
