### ISSUE TITLE
Y大好，怎么解密？？看着不是BASE64呢。

### ISSUE THREAD

**Issue by liker5092** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#72]
z="
";lNCz='Slli';rKCz='cEpV';jcCz='MHdU';PUCz='RWRY';VYBz='MnhX';nACz='M1ZX';pz='ZFEK';GHBz='ZFVi';Zdz='Clkz';TgBz='NApR';AhCz='RlNh';vJBz='SmFS';LmBz='d1dR';KRBz='R0py';XPCz='eG9i';LkBz='MEpZ';yhCz='WlVG';mwz='bXMx';KmCz='RVNr';ODz='S1Yy';UDBz='QmFV';bHBz='WGhV';mCCz='bTEw';skz='V2to';qBCz='R3RW';GZBz='M2h6';Oez='d3BX';GFCz='TldG';bbBz='ZEhh';QTz='c1dr';pBCz='S2VG';RVCz='MXA1';QCBz='bUZP';XHBz='Q21O';VkCz='YzFa';mbCz='SFJQ';sJz='cEhi';Fkz='VnBy';SKz='WnNX';mDBz='MkV6';DGCz='VkZj';QcBz='a3Bs';umCz='U0ln';dkBz='RXlh';bRCz='aGhZ';buBz='RlRD';sZBz='QnBV';InCz='"';KTBz='VmtX';Duz='RXhj';fxz='VnBa';PPz='UjFw';yfz='MTRX';vUBz='MnN4';UQz='YzA1';LEz='MFpa';Lz='YXNl';dVz='Rlph';Qjz='eFZX';CvBz='V05H';YJz='ZDA1';DRCz='ZEFw';Maz='M2ho';Vvz='Qk9W';fACz='

前数百个字符。

**Comment by yonggekkk** [comment]
要就发邮箱好了

**Comment by liker5092** [comment]
rmbrgb#qq.c0m.....

你懂得。TKU

**Comment by yonggekkk** [comment]
> rmbrgb#qq.c0m.....
> 
> 你懂得。TKU

用国外邮箱

**Comment by liker5092** [comment]
gooaest#gmail.c0m...
你懂得。。。

**Comment by yonggekkk** [comment]
已发

**Comment by yonggekkk** [comment]
已发送
