### ISSUE TITLE
win端不识别hy订阅链接

### ISSUE THREAD

**Issue by Ren9527** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#76]
![hy](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/24719953/afda2d8b-74ac-4e01-9335-e28f2cae2340)
该项目的linux端生成的订阅，win端都不认。。。

**Comment by yonggekkk** [comment]
你这是单节点分享链接，不是订阅！看下第三期视频教程
