### ISSUE TITLE
Missing Argo Link/QR

### ISSUE THREAD

**Issue by ghargha** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#79]
Hello,

First, thank you very much for your work. very professional.

I saw two issues which I decided to share with you:

1) The `Argo` connection is not generated
2) When we enter the VPS domain for SSL verification, some connections such as the `TUIC` do not work, but they work when we don't use the domain SSL certification and we use self-encryption instead

**Comment by yonggekkk** [comment]
Every time you change the settings, you must select 9, configure and re-output. If you are not sure about the configuration of your change, you can refer to my related video tutorial.
