### ISSUE TITLE
最近会一直卡在这个界面上，需要很长时间才能进入输入命令界面

### ISSUE THREAD

**Issue by zhuxining** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#82]
多次试过重启和 `control+c` ，还是会卡在这个界面。
另外，之前vless-reality和Vvmess-WS-iZ可以使用，现在只有vless-reality能用，其他Vvmess、hysteria2、tuic5都不通了。

![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/12285468/bd49256f-e8bd-4fec-8101-eedc176308c9)

**Comment by yonggekkk** [comment]
重启下VPS再试试
