### ISSUE TITLE
功能建议：Argo通道失效后自动重建

### ISSUE THREAD

**Issue by bumprat** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#83]
首先万分感谢yonggekkk，感谢制作这么好的工具。

## 问题现象：

服务器配置Argo固定通道，客户端测试正常。当服务器网络环境受到扰动后，CF通道状态转为关闭`Down`，客户端无法上网。检查服务器状态信息中，`Argo固定域名`信息不再显示，3-3-2设置Argo固定通道，可以看到之前的配置都在。

重新重复输入Argo通道Token和域名后，CF通道状态恢复为健康`healthy`。

## 功能建议：

服务器网络环境受到扰动后，CF的通道"破裂"，此时程序应该利用之前的配置自动重建Argo固定通道。

**Comment by yonggekkk** [comment]
目前已更新，选择更新脚本，再重置下固定隧道即可

**Comment by bumprat** [comment]
收到，感谢！

**Comment by bumprat** [comment]
经测试，还是存在argo固定通道中断问题（美vps）。经测试，建议增加argo通道http2协议（默认为优先quic），同时增加重试次数。以下为详细情况：

# cloudflared Argo 通道频繁关闭

源代码中，使用了 crontab 在@reboot 时运行 cloudflared：

```sh
@reboot /bin/bash -c "nohup setsid /etc/s-box/cloudflared tunnel  ...
```

但实际情况是，服务器不重启的情况下，argo 通道频繁关闭，需要手动重启服务器或重置 argo 配置。

查看 cloudflared 日志`/etc/s-box/argo.log`中频繁（每天一次）显示

```
2024-08-12T06:24:21Z ERR Failed to serve quic connection error="timeout: no recent network activity" connIndex=0 event=0 ip=...
2024-08-12T06:24:21Z ERR Serve tunnel error error="timeout: no recent network activity" connIndex=0 event=0 ip=...
2024-08-12T06:24:21Z INF Retrying connection in up to 1s connIndex=0 event=0 ip=...
2024-08-12T06:24:22Z ERR Connection terminated error="timeout: no recent network activity" connIndex=0
```

经互联网查找上述错误：[新版 cloudflared 默认使用 QUIC 协议可能是问题根源](https://forums.unraid.net/topic/139806-cloudflared-container-tunnel-connections-quic/)

## 解决方案：

[修改协议类型](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-run-parameters/#protocol)，默认是 auto，修改为 http2

[增加重试次数](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-run-parameters/#retries)，默认是 5 次，每次间隔 2^n 秒，5 次是 1+2+4+8+16=31 秒

```
nohup setsid /etc/s-box/cloudflared tunnel --no-autoupdate --edge-ip-version auto --protocol http2 --retries 9...
```

或者

```
nohup setsid env TUNNEL_TRANSPORT_PROTOCOL=http2 TUNNEL_RETRIES=9 /etc/s-box/cloudflared tunnel ...
```

**Comment by yonggekkk** [comment]
是这个问题吗？那到时我改为HTTP2吧

**Comment by bumprat** [comment]
经过1个月测试，按上面的说明修改配置后，再也没有出现过通道破裂/关闭的问题。
