### ISSUE TITLE
域名申请

### ISSUE THREAD

**Issue by fengzaixing401** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#84]
甬哥你好，.tk域名已经添加到cf解析，脚本申请域名显示：
“经检测，你正在使用freenom免费域名解析，不支持当前DNS API模式，脚本退出”

**Comment by yonggekkk** [comment]
freenom免费域名不支持DNS api。。。用常规的80端口申请吧

**Comment by fengzaixing401** [comment]
我之前用的一个其他作者的x-ui脚本，可以用acme的dns api模式申请，但是没办法导入.
