### ISSUE TITLE
申请Let’s Encrypt证书出错，换成ZeroSSL正确，希望能获取当前版本源码，改一下。谢谢甬哥

### ISSUE THREAD

**Issue by iStarryTree** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#87]
日志：Invalid status, h.域名:Verify error detail:DNS problem: looking up A for h.域名: DNSSEC: DNSKEY Missing; DNS problem: looking up AAAA for h.域名: DNSSEC: DNSKEY Missing
好像是和.top域名有关
邮箱：starry_tree@outlook.com
谢谢甬哥

**Comment by yonggekkk** [comment]
有空更新下

**Comment by iStarryTree** [comment]
甬哥能发下源码吗，目前脚本好像只能走Let’s Encrypt才会自动配置出节点链接。邮箱：starry_tree@outlook.com

**Comment by yonggekkk** [comment]
脚本只能acme，不支持ZeroSSL

**Comment by iStarryTree** [comment]
acme支持zerossl证书
![image](https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/assets/35221958/baa91744-7785-43a1-af84-c0785239e614)

**Comment by yonggekkk** [comment]
> acme支持zerossl证书 ![image](https://private-user-images.githubusercontent.com/35221958/344384862-baa91744-7785-43a1-af84-c0785239e614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MDAyNjQsIm5iZiI6MTcxOTY5OTk2NCwicGF0aCI6Ii8zNTIyMTk1OC8zNDQzODQ4NjItYmFhOTE3NDQtNzc4NS00M2ExLWFmODQtYzA3ODUyMzllNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDIyMjYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTVmZmY5NTdkOWVkMzRjOTQ2NmU4NjAzZGQ3ZGMwYTFiYmM4NTFlY2M5MjkyMWNmNjBkZjI5MzgxM2RjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sgasa6KUItHOx_UVngbQgsAjUmVEnuRiLuX_3kDLdI4)

但是脚本没加入
