### ISSUE TITLE
想问以下 输出的订阅如何配置到Clash中呢？ 

### ISSUE THREAD

**Issue by chengzi0103** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#89]
我使用勇哥的配置  然后把它变成了clash的配置，但是在ubuntu中的clash导入之后，无法使用
但是在v2rayn/shadowrocket是可以使用的

**Comment by yonggekkk** [comment]
脚本集成gitlab订阅会自动生成，不然的话你就要通过网络上的第三方转换生成吧。
