### ISSUE TITLE
sing-box_hysteria2_tuic_argo_reality   argo隧道端口号多少？设置成http://127.0.0.1:8089不通，http://localhost:8001也不通，http://localhost:8080、http://localhost:8089都不通。

### ISSUE THREAD

**Issue by ssfeng72** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#95]
sing-box_hysteria2_tuic_argo_reality
  argo隧道端口号多少？设置成http://127.0.0.1:8089不通，http://localhost:8001也不通，http://localhost:8080、http://localhost:8089都不通。

**Comment by yonggekkk** [comment]
https://github.com/yonggekkk/sing-box_hysteria2_tuic_argo_reality/issues/94
