### ISSUE TITLE
argo老自动关闭，怎么解决。就是其它都通，只有argo显示关闭，重新设置一下argo就又通了，这种情况怎么解决

### ISSUE THREAD

**Issue by ssfeng72** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#96]
argo老自动关闭，怎么解决。就是其它都通，只有argo显示关闭，重新设置一下argo就又通了，这种情况怎么解决

**Comment by yonggekkk** [comment]
什么vps？dd过吗

**Comment by ssfeng72** [comment]
dci便宜小鸡，限定
![Uploading 17243753871062528955684423821609.jpg…]()
端口范围20651-20700。

**Comment by yonggekkk** [comment]
按视频教程来
