### ISSUE TITLE
hy2yaml添加bandwidth limitation未生效

### ISSUE THREAD

**Issue by redcats2** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#97]
问题：
在/etc/s-box/v2rayn_hy2.yaml 添加“bandwidth”未生效：
----------------
server: "9.9.9.9:40267,10000-50000"
auth: c669778c-aaaa-aaaa-aaaa-aaaaaaaaa
tls:
  sni: www.bing.com
  insecure: true
fastOpen: true
socks5:
  listen: 127.0.0.1:50000
lazy: true
transport:
  udp:
    hopInterval: 30s
bandwidth:
  up: 0.06 gbps
  down: 0.06 gbps
--------------

原因：
v2rayN的sing-box模式不支持speedlimit，考虑从服务端限制，但测试未生效，请问是否不支持？

参考文档：
https://v2.hysteria.network/docs/advanced/Full-Server-Config/

**Comment by yonggekkk** [comment]
客户端设置就行
