### ISSUE TITLE
网络小白向大佬请教一下，24小时内能用一个设备（IP）同时sing-box设置的节点连通外网这个状况正常吗？

### ISSUE THREAD

**Issue by sniperjin198** [yonggekkk/sing-box_hysteria2_tuic_argo_reality#98]
用的是vultr的vps
使用的bash <(curl -Ls https://gitlab.com/rwkgyg/sing-box-yg/raw/main/sb.sh) 这个脚本一键配置节点
配置好后使用V2rayN（电脑端）和V2rayNG（手机端）连接，VLESS和VMESS节点可以正常使用。
想请教
本地使用了2个设备，一个电脑和电脑分享热点的一台笔记本，实际情况是用笔记本使用VMESS节点连接后，电脑使用VMESS连接就不成功，但使用VLESS节点可以连接。当天如果白天用电脑连接了，晚上用手机（4g网络）什么节点都连不通
如果早晨先用手机（4g网络）使用VMESS节点连通了，电脑上vmess和vless节点就都连不通了，重启sing-box之后又可以重新连通。

请教一下，这是正常的状况吗？我能否在sing-box里设置同时允许2个或者3个不同的IP同时连接？

**Comment by yonggekkk** [comment]
没有同时允许连接的设置，本身就可以无限的设备连接呀。。可能是你网络问题

**Comment by sniperjin198** [comment]
感谢大佬指点

**Comment by sniperjin198** [comment]
> 没有同时允许连接的设置，本身就可以无限的设备连接呀。。可能是你网络问题

感谢大佬指点
